name: Build Signed APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode Keystore
        run: |
          # Project root dhoondo jahan settings.gradle ya build.gradle hai
          PROJECT_DIR=$(dirname $(find . -maxdepth 3 -name "settings.gradle*" -o -name "build.gradle*" | head -n 1))
          echo "PROJECT_DIR is $PROJECT_DIR"
          
          # Keystore file project folder ke andar decode karo
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > "$PROJECT_DIR/ruby-release.keystore"
          ls -la "$PROJECT_DIR"

      - name: Build Signed APK
        run: |
          # Android project ke folder mein jaa kar build run karo
          PROJECT_DIR=$(dirname $(find . -maxdepth 3 -name "settings.gradle*" -o -name "build.gradle*" | head -n 1))
          cd "$PROJECT_DIR"
          
          gradle assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/ruby-release.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ruby-Signed-APK
          path: "**/build/outputs/apk/release/*.apk"
